class HomeItemModel {
  String chefImg;
  String chefName;
  String img;
  String name;
  String foodtype;
  String duration;
  String likesCount;
  String description;
  List<String> ingredients;
  List<String> recipesSteps;
  bool favorite;

  HomeItemModel(
      this.chefImg,
      this.chefName,
      this.img,
      this.name,
      this.foodtype,
      this.duration,
      this.likesCount,
      this.description,
      this.ingredients,
      this.recipesSteps,
      this.favorite);
}

List<HomeItemModel> homeModel = [
  HomeItemModel(
    "assets/images/karina.jpeg",
    "Karina",
    "assets/images/nasgor.jpeg",
    "Nasi Goreng Special",
    "Food",
    "> 20 min",
    "260",
    "Nasi goreng menjadi salah satu menu makanan khas Indonesia yang cukup terkenal di berbagai negara lain. Bahkan, kamu bisa menemukan makanan ini dengan mudah di berbagai tempat. Bahan dasarnya yang terbuat dari nasi membuat makanan ini cocok untuk dimakan berbagai kalangan, mulai dari anak-anak hingga lansia. Selain itu, beragam sayuran yang menarik juga bisa menambahkan kandungan nutrisi pada makanan ini. Agar nasi goreng yang kamu konsumsi semakin lezat dan sehat, kamu bisa membuat nasi goreng dengan resep praktis berikut ini!",
    [
      "2 porsi nasi",
      "50gr daging ayam potong dadu",
      "2 butir telur",
      "3 siung bawang merah, cincang kecil",
      "2 bawang putih, cincang kecil",
      "2 batang daun bawang, potong",
      "1 buah cabai keriting",
      "1 sdm kecap manis",
      "2 sdm kecap ikan",
      "1 sdm saus tiram",
      "1/2 sdt kecap asin",
      "1/2 sampai 1 sdm gula",
      "1/2 sdt merica",
      "1/2 sdt margarin",
      "1 sdt kaldu jamur",
      "Minyak untuk menumis",
    ],
    [
      "Panaskan sedikit minyak di wajan, lalu tumis ayam hingga matang dan kemudian  sisihkan.",
      "Di wajan yang sama, panaskan sedikit minyak dan orak-arik telur sampai matang. Kemudian, masukkan semua bawang dan cabai. Aduk dan tumis hingga matang.",
      "Masukan nasi, aduk hingga rata. Lalu, masukkan ayam suwir, dan semua bahan kecap, garam, merica, dan kaldu jamur, aduk kembali sampai rata.",
      "Koreksi rasa. Jika sudah pas, angkat dan sajikan dengan lalapan timun atau selada.",
    ],
    true,
  ),
  HomeItemModel(
    "assets/images/karina.jpeg",
    "Karina",
    "assets/images/rawon.jpg",
    "Rawon",
    "Food",
    "> 80 min",
    "100",
    "Rawon adalah semacam sup daging sapi kaya rempah-rempah dengan warna hitam pekat yang berasal kluwek. Makanan khas Jawa Timur ini memiliki rasa yang gurih dengan cita rasa rempahnya yang kuat. Bukan itu saja, daging rawon pun terkenal empuk sehingga mudah sekali untuk dikunyah. Hidangan ini umumnya disajikan bersama nasi putih, tauge, telur asin, irisan daun bawang, dan sambal. Berikut resep rawon yang bisa kamu coba!",
    [
      "1/2 kg daging sapi ",
      "7 siung bawang merah ",
      "5 siung bawang putih",
      "3 butir kemiri (sangrai)",
      "2 ruas jari kunyit ",
      "7 gr jahe",
      "5 butir kluwek",
      "3 lembar daun salam",
      "6 lembar daun jeruk",
      "Lengkuas, geprek",
      "2 batang serai, geprek",
      "50 gr gula merah",
      "1 sdt gula pasir",
      "1 1/2 sdt garam",
      "2 sdt kaldu sapi bubuk",
      "1/4 sdt merica bubuk",
      "1/4 sdt ketumbar bubuk",
      "1 1/2 liter air rebusan daging sapi",
    ],
    [
      "Rebus daging sapi hingga mendidih dan kotorannya keluar. Buang air rebusan sapi kemudian rebus kembali dengan air bersih hingga matang. Angkat, tiriskan lalu potong-potong sesuai selera.",
      "Keluarkan daging kluwek dari cangkangnya, pastikan rasanya tidak pahit. Setelah itu, rendam kluwek di air panas dan sisihkan.",
      "Haluskan bawang merah, bawang putih, kemiri, dan jahe. Bisa diblender atau diulek hingga benar-benar halus.",
      "Campurkan kluwek dengan bumbu halus dan haluskan bersama hingga tercampur merata.",
      "Panaskan minyak, tumis bumbu halus. Tambahkan daun salam, daun jeruk yang disobek-sobek, serai, dan lengkuas. Tumis dengan api kecil hingga matang dan tanak.",
      "Masukkan daging dan air rebusan daging. Aduk dan tunggu mendidih. Tambahkan garam, gula, gula merah, kaldu sapi bubuk, merica bubuk, dan ketumbar bubuk.",
      "Jika sudah matang, angkat dan sajikan. Anda juga bisa menambahkan kecambah sebagai topping untuk disantap bersama nasi hangat.",
    ],
    true,
  ),
  HomeItemModel(
    "assets/images/karina.jpeg",
    "Karina",
    "assets/images/perkedel.jpg",
    "Perkedel Isi Ayam",
    "Food",
    "> 90 min",
    "50",
    "Perkedel adalah makanan olahan kentang berbentuk bulat yang digoreng. Resep perkedel kentang yang gurih dan lezat ini bisa kamu buat sendiri di rumah. Caranya cukup mudah, tinggal tumbuk kentang hingga halus, campur dengan bumbu dan irisan daun bawang, lalu celupkan ke dalam kocokan telur, lalu goreng dengan api sedang. Kamu juga bisa membuat perkedel kentang dengan berbagai isian, yuk simak resepnya di sini!",
    [
      "1 kilogram kentang.",
      "200 gram daging ayam giling.",
      "4 siung bawang putih.",
      "4 butir bawang merah.",
      "2 sdt garam(secukupnya).",
      "1/2 sdt penyedap rasa.",
      "1 butir kuning telur.",
      "2 putih telur.",
    ],
    [
      "Kupas kentang dan potong menjadi kecil-kecil, lalu rebus sampai matang. Angkat dan tiriskan. Kemudian, haluskan kentang rebus.",
      "Selanjutnya, iris bawang merah dan bawang putih, lalu goreng.",
      "Campur daging ayam giling dan kentang yang sudah dihaluskan, lalu tambahkan bawang goreng, garam, kuning telur dan penyedap.",
      "Bentuk perkedel menjadi bulat dengan besarnya sesuai selera.",
      "Setelah itu, panaskan minyak. Celupkan perkedel ke dalam putih telur, lalu goreng hingga matang.",
      "Nikmati perkedel selagi hangat.",
    ],
    false,
  ),
  HomeItemModel(
    "assets/images/karina.jpeg",
    "Karina",
    "assets/images/balado.jpg",
    "Telur Balado",
    "Food",
    "> 60 min",
    "20",
    "Telur balado adalah salah satu hidangan lezat yang sangat populer di Indonesia. Hidangan yang berasal dari Sumatera Barat ini terkenal karena cita rasa pedasnya yang khas dan menggugah selera. Kamu bisa temukan hidangan ini di berbagai restoran, warung makan, atau buat sendiri di rumah. Untuk membuat telur balado, kamu memerlukan beberapa bahan sederhana. Seperti telur rebus dan bumbu balado yang terbuat dari bawang merah, bawang putih, cabai merah, tomat, gula, garam, dan minyak goreng. Yuk cek resep lengkapnya!",
    [
      "1/2 kg telur",
      "200 gr cabai merah",
      "4 butir bawang merah",
      "1 siung bawang putih",
      "1 buah tomat merah",
      "Garam, secukupnya",
      "Penyedap rasa, secukupnya",
      "Minyak, secukupnya",
    ],
    [
      "Rebus telur sampai matang, setelah itu kupas dan goreng sampai kuning keemasan. Angkat dan sisihkan.",
      "Haluskan cabai, bawang merah, bawang putih, tomat. Tambahkan sedikit garam dan penyedap.",
      "Setelah itu, tumis bumbu halus hingga harum dan matang.",
      "Matikan api, kemudian masukan telur yang sudah kamu goreng. Setelah itu, aduk dan koreksi rasa. Sajikan dengan nasi hangat.",
    ],
    false,
  ),
  HomeItemModel(
    "assets/images/sohe.jpg",
    "Han So Hee",
    "assets/images/martabak-mini.jpg",
    "Martabak Mini Pandan",
    "Food",
    "> 60 min",
    "30",
    "Martabak mini adalah versi kecil dari martabak yang merupakan salah satu makanan jalanan populer di Indonesia. Ada dua jenis utama martabak yang biasa dikenal, yaitu martabak manis (juga dikenal sebagai terang bulan) dan martabak telur. Versi mini ini menawarkan ukuran yang lebih kecil dan praktis, sehingga cocok untuk dijadikan camilan atau makanan ringan.",
    [
      "Tepung terigu 125 g",
      "Air matang 150 ml",
      "Sari pandan 30 ml",
      "Margarin 3 sdm",
      "Gula pasir 3 sdm",
      "Telur ayam 1 butir",
      "Ragi instan (Fermipan) 1/4 sdt",
      "Baking powder 1/2 sdt",
      "Susu kental manis secukupnya",
      "Toping mesis cokelat, keju, atau kacang cincang kasar.",
    ],
    [
      "Campur tepung terigu, gula pasir, ragi instan, baking powder, sari pandan",
      "Aduk-aduk adonan sambil ditambah air matang sedikit demi sedikit",
      "Aduk adonan sampai tercampur merata dan tidak ada yang menggumpal",
      "Diamkan adonan hingga 30 menit",
      "Cairkan margarin dan kocok telur ayam, masukan ke dalam adonan",
      "Panaskan loyang martabak mini lalu oles dengan margarin",
      "Tuangkan adonan ke setiap cetakan loyang martabak mini",
      "Tabur gula sedikit ke atas permukaan",
      "Setelah adonan matang, angkat lalu taburkan toping sesuai selera.",
    ],
    false,
  ),
  HomeItemModel(
    "assets/images/gyj.jpg",
    "Go Yoon Jung",
    "assets/images/thaitea.jpg",
    "Thai Tea",
    "Drink",
    "> 30 min",
    "40",
    "Thai Tea merupakan minuman kekinian yang sangat populer beberapa tahun terakhir ini. Thai Tea adalah minuman asal Thailand terbuat dari teh, susu, dan gula yang disajikan hangat atau dingin.",
    [
      "1500 ml air",
      "50 gr daun Thai Tea atau bisa pakai teh hitam",
      "125 gr gula pasir",
      "200 ml susu evaporasi",
      "350 ml krimer/ susu kental manis putih",
      "Es batu secukupnya",
    ],
    [
      "Rebus air bersama daun teh hingga mendidih.",
      "Matikan api, tutup panci. Biarkan selama 5 menit hingga berubah warna menjadi pekat.",
      "Saring teh, lalu tambahkan gula. Aduk rata, biarkan agak dingin.",
      "Campurkan kembali dengan susu evaporasi dan krimer atau susu kental manis. Aduk rata.",
      "Sajikan bersama es batu.",
    ],
    false,
  ),
  HomeItemModel(
    "assets/images/karin.jpg",
    "Fujiyoshi Karin",
    "assets/images/ramen.jpg",
    "Mie Ramen",
    "Food",
    "> 60 min",
    "30",
    "Martabak mini adalah versi kecil dari martabak yang merupakan salah satu makanan jalanan populer di Indonesia. Ada dua jenis utama martabak yang biasa dikenal, yaitu martabak manis (juga dikenal sebagai terang bulan) dan martabak telur. Versi mini ini menawarkan ukuran yang lebih kecil dan praktis, sehingga cocok untuk dijadikan camilan atau makanan ringan.",
    [
      "3 sdm minyak untuk menumis",
      "3 siung bawang putih cincang",
      "2 cm jahe segar memarkan",
      "2 sdm daun bawang iris halus",
      "200 gram daging sapi top round cincang",
      "3 buah cabai rawit merah segar haluskan",
      "2 sdm selai kacang halus",
      "2 sdm shoyu (kecap asin khas Jepang) atau kecap asin",
      "1 sdt garam",
      "1 sdt merica bubuk",
      "1 sdt gula pasir",
      "500 gram ramen segar atau ramen beku siap pakai",
      "8 g (1 bungkus) Royco kaldu sapi",
      "1 liter air",
      "1 sendok makan minyak cabai",
    ],
    [
      "Rebus 1 liter air hingga mendidih. ",
      "Sambil menunggu, tumis bawang putih, jahe segar, dan daun bawang hingga harum. Masukkan ke dalam rebusan air setelah mendidih ",
      "Masukkan tumisan daging sapi cincang beserta cabai rawit merah halus, selai kacang, shoyu, garam, merica bubuk, dan gula pasir. ",
      "Setelah daging terlihat matang dan empuk, masukkan ramen dan aduk-aduk perlahan",
      "Tunggu hingga ramen matang dan aromanya harum, matikan api dan ramen siap dihidangkan.",
    ],
    false,
  ),
];
